loss: "CrossEntropyLoss"
optimizer:
  name: "Adam"
  params:
    lr: 0.0001
    weight_decay: 0.001
scheduler:
  name: none
  params:
    lr_lambda: 0.65
oversample: True
epochs: 1
train_dataloader:
  batch_size: 16
  num_workers: 4
  shuffle: True
valid_dataloader:
  batch_size: 1
  num_workers: 4
  shuffle: False
log_step: 25